// One-off: pull latin + latin-ext woff2 subsets from Google Fonts and write
// them plus an @font-face sheet into public/fonts. Fonts are committed so the
// app never depends on a third-party font host at runtime.
import { mkdir, writeFile } from "node:fs/promises";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

// Display is Baloo 2 (the "F.", the wordmark, every headline) and the
// ampersand device is Nunito — one rounded system, deliberately narrow.
const FAMILIES = [
  { spec: "Baloo+2:wght@500..800", file: "baloo2", family: "Baloo 2 Variable" },
  // Nunito ships for exactly one glyph — the ampersand device — so it is
  // subset to that single character rather than pulling a full latin set.
  { spec: "Nunito:wght@400..1000", file: "nunito-amp", family: "Nunito Amp", text: "&" },
  { spec: "Inter:wght@400..700", file: "inter", family: "Inter Variable" },
  { spec: "JetBrains+Mono:wght@400..600", file: "jetbrains-mono", family: "JetBrains Mono Variable" },
];

const WANTED = new Set(["latin", "latin-ext"]);

await mkdir(new URL("../public/fonts/", import.meta.url), { recursive: true });

let sheet = "/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n";

for (const { spec, file, family, text } of FAMILIES) {
  const query = `family=${spec}&display=swap${text ? `&text=${encodeURIComponent(text)}` : ""}`;
  const css = await fetch(`https://fonts.googleapis.com/css2?${query}`, {
    headers: { "user-agent": UA },
  }).then((r) => r.text());

  // A `text=` request comes back as a single unnamed subset with no
  // unicode-range, so handle it separately from the named-subset case.
  if (text) {
    const url = css.match(/https:\/\/fonts\.gstatic\.com[^)]+/)?.[0];
    const weight = css.match(/font-weight:\s*([^;]+);/)?.[1] ?? "400";
    if (!url) throw new Error(`no font url for ${spec}`);
    const name = `${file}.woff2`;
    const bytes = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
    await writeFile(new URL(`../public/fonts/${name}`, import.meta.url), bytes);
    sheet +=
      `\n@font-face {\n` +
      `  font-family: "${family}";\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${weight.trim()};\n` +
      `  font-display: swap;\n` +
      `  src: url("/fonts/${name}") format("woff2-variations");\n` +
      `}\n`;
    console.log(`${name} — ${(bytes.length / 1024).toFixed(1)}kb (subset: ${text})`);
    continue;
  }

  // Google emits `/* subset */ @font-face { ... }` blocks in order.
  const blocks = css.split("/*").slice(1);
  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf("*/")).trim();
    if (!WANTED.has(subset)) continue;
    const url = block.match(/https:\/\/fonts\.gstatic\.com[^)]+/)?.[0];
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];
    const weight = block.match(/font-weight:\s*([^;]+);/)?.[1] ?? "400";
    const stretch = block.match(/font-stretch:\s*([^;]+);/)?.[1];
    if (!url || !range) continue;

    const name = `${file}-${subset}.woff2`;
    const bytes = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
    await writeFile(new URL(`../public/fonts/${name}`, import.meta.url), bytes);

    sheet +=
      `\n@font-face {\n` +
      `  font-family: "${family}";\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${weight.trim()};\n` +
      (stretch ? `  font-stretch: ${stretch.trim()};\n` : "") +
      `  font-display: swap;\n` +
      `  src: url("/fonts/${name}") format("woff2-variations");\n` +
      `  unicode-range: ${range.trim()};\n` +
      `}\n`;
    console.log(`${name} — ${(bytes.length / 1024).toFixed(1)}kb`);
  }
}

await writeFile(new URL("../public/fonts/fonts.css", import.meta.url), sheet);
